### ISSUE TITLE
Допускаются ли в системе сценарии, при которых админ не будет являться пользователем?

### ISSUE THREAD

**Issue by coursar** [eybv/blog-engine#6]
https://github.com/eybv/blog-engine/blob/475fb6c6af9af133aa61b823a5f1780ba27e3df0/src/main/java/com/github/eybv/blog/engine/controller/PostController.java#L72

**Comment by eybv** [comment]
Роль пользователя по умолчанию добавляется всем аккаунтам при регистрации, предполагается что любой администратор также является пользователем.

В текущей версии может получиться ситуация когда администратор не будет являться пользователем, если он сам или другой администратор удалит эту роль, так как в сервисе нет проверки какую именно роль пытаются удалить.

Предусмотрено что в аннотацию ```@HasRole``` можно передать список ролей ```@HasRole({"ROLE_USER", "ROLE_ADMIN"})```, но так как удаление роли пользователя **является багом**, а не ожидаемым поведением, везде используется вариант с одной ролью.
